### ISSUE TITLE
CMSMonitoring python package leaving open file descriptors behind

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#166]
As reported in this WMCore GH issue/comment:
https://github.com/dmwm/WMCore/issues/11289#issuecomment-1252335852

we have been having problem with the WMAgent component (AgentStatusWatcher) that uses the CMSMonitoring library to upload data to AMQ.

We are now using version `0.6.8`, which includes heartbeat functionality. So it could be that this issue is either on the CMSMonitoring side or in the `stomp.py` dependency (currently using `7.0.0`).

The previous stable WMAgent release was using CMSMonitoring `0.3.4`, and it was working just fine (it didn't have the heartbeat feature though).

Could you please help us investigating what the problem is?

**Comment by mrceyhun** [comment]
@amaltaro sorry I did not see I was mentioned in the WMCore issue. I am looking it immediately.

**Comment by mrceyhun** [comment]
@amaltaro it can be related with https://github.com/dmwm/CMSMonitoring/blob/master/src/python/CMSMonitoring/StompAMQ7.py#L341 which I intentionally disabled the disconnection after "each send" because it was disconnecting immediately and did not send data. At that time, there was no solution for that. 

It seems this issue is solved in [v8.0.0](https://github.com/jasonrbriggs/stomp.py/compare/v7.0.0...v8.0.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR12), let me upgrade our StompAMQ to latest v8.0.1 version and test it.

**Comment by amaltaro** [comment]
Thanks for the prompt feedback, @mrceyhun . If you find a way to provide a CMSMonitoring-only fix, that will be easier to push changes upstream to services already deployed in production.

Upgrade to this latest stomp.py version is likely better to go through our/WMCore usual deployment schedule, if possible.

**Comment by amaltaro** [comment]
@mrceyhun Ceyhun, we have been using in WMCore the cmsmonitoring `0.6.9` version without any problems. Shall we close this ticket?

**Comment by mrceyhun** [comment]
@amaltaro Thanks for reminding. We are also using this version in production without any problem. Fixed with https://github.com/dmwm/CMSMonitoring/pull/167
