### ISSUE TITLE
monit.py line #71: 'es-cms': 8983,

### ISSUE THREAD

**Issue by bockjoo** [dmwm/CMSMonitoring#21]
Hi Valentin,
I think it should be
'cms':8983,
instead. 
Using this json:
{"query": {"match_all": {}}, "from":0, "size": 10}
, 
python monit.py --query=q.match_all.json --token ~/services/xrootd-summary-collector/SummaryCollector/token.txt --dbname=es-cms
does not work.

But if I add 'cms':8983, to the DBDICT,
python monit.py --query=q.match_all.json --token ~/services/xrootd-summary-collector/SummaryCollector/token.txt --dbname=cms
works.
Is there any other way to make dbname=es-cms work?
Thanks,
Bockjoo

**Comment by vkuznet** [comment]
Bockjoo, so far I renamed it internally, now you can use both names. I need to talk to CERN MONIT team to find out why we can't use es-cms name in ES proxy

**Comment by vkuznet** [comment]
ok, upon further look-up I understood the problem. The dbname is used to compose and index name of ES query, e.g.
```
{"search_type": "query_then_fetch", "ignore_unavailable": True, "index": [dbname]}
```
Since the ES database is es-cms.cern.ch I used es-cms name, but in this database the index name is `cms*` and that's the reason why it does not work.

So the DBDICT should contain mapping of ES indexes.

Therefore I the solution I applied: to treat `es-cms` as `cms` seems reasonable. If you want I can remove es-cms complete.

Closing the ticket now.
