### ISSUE TITLE
job classads with "None" or set as Undefined?

### ISSUE THREAD

**Issue by amaltaro** [dmwm/CMSMonitoring#3]
Instead of having the always misleading None string ("None") in the classads schema, how about we use the Undefined value, as is already used by a few other job classads, e.g.:
https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/BossAir/Plugins/SimpleCondorPlugin.py#L579

**Comment by amaltaro** [comment]
@belforte

**Comment by amaltaro** [comment]
And I just got confused by something else. Is that schema
https://github.com/dmwm/CMSMonitoring/blob/master/schemas/ClassAds.json

meant to be an schema for the job classads attributes? Or for what's going to show up in MonIT?
If the former, then I'd suggest to also fix the attribute names, given that we decided to prefix them with `CMS_`, so we better make it crystal clear.

**Comment by belforte** [comment]
@amaltaro 
Well... in the line you point to it is really No, I do not want any dataset. Rather then 'I do not know which dataset I want'. So 'None' makes sense from classification p.o.v. Of course it is confusing in python land since None is a special value there, not just a string. Besides UNDEFINED is a well defined keyword in HTCondor to indicate ClassAds which have not been defined :-) allowing to use ads in expressions  if they may not be present. Maybe we can simply capitalize to NONE to make it clear it is our string, not the python None ? 

As to the schema, indeed it is the monitoring attributes, not the classAds used to communicate them form WM tools to MONIT feeder. I guess a comment can be added to the file to clarify. You can e.g. make a PR !

**Comment by vkuznet** [comment]
Alan, the https://github.com/dmwm/CMSMonitoring/blob/master/schemas/ClassAds.json is just reflection of https://docs.google.com/spreadsheets/d/1x73SxboZqNvpYKHmaJ9PioT3itpw4qQrTjUecnKLTi4/edit#gid=0 document we discussed. So it is what we want to store to Monitoring as high level information. The actual schema of sub-system docs will be JSON docs (similar to WMArchive schema) where each sub-system will create a schema file with all attribute-value pairs this sub-system will use to inject docs into MONIT. The important point here that the ClassAds.json will be used to verify that we inject this mandatory attributes and their values would what this ClassAds.json have. While the schema files for sub-systems (e.g. WMAgent, CRAB) will be given t use by these sub-systems and we'll validate each doc against it. The latter is work in progress. So far I come up with validation code for a schema, next week will distribute proposal how actual validation will work and what we will require from each sub-system.

**Comment by vkuznet** [comment]
If you're ego to know, you can review it now, see https://its.cern.ch/jira/browse/CMSMONIT-67

**Comment by vkuznet** [comment]
Regarding None vs "NONE", each document should follow its own schema, therefore if attribute should be string data-type you better use "NONE" since None data-type is not equal to "NONE".

**Comment by vkuznet** [comment]
I'm in favor of full names instead of shortcuts, so
PrimaryInputType is better to my taste then PrimaryInpType because it makes it
clear to read and understand.

Feel free to submit necessary changes to this repository and fix the doc (which
is open for editing).
