### ISSUE TITLE
Some comments on usage

### ISSUE THREAD

**Issue by stiegerb** [dmwm/CMSMonitoring#8]
Hi @vkuznet,
I'm trying to set up cms-htcondor-es to use the validation code via CMSMonitoring/StompAMQ, and I have some comments on the usage. I'll also prepare a PR with my suggested changes:

- Maybe it would be easier if the validation happened in `make_notification` rather than in the send method. That way one could choose to reject individual documents that fail validation.

- I think the users should be able to specify which schema will be used for validation when instantiating StompAMQ. It shouldn't be the default for the code to guess which schema is being used. In case the validation happens in `make_notification` as in the previous point, users could specify which schema to use for each document, allowing for the possibility of one StompAMQ instance sending documents with several different schemas (since we already allow different doc types). We could set a default schema when instantiating StompAMQ and use that if none is provided. If none is provided, we could fall back to guessing.

- I think it should fall to the users to handle validation failures. I would suggest `make_notification` issues a logging.warning (or error?) when the validation fails and returns a bool with the result. Users can then keep track of documents that fail without dropping other documents in the same batch that pass validation.

Let me know what you think,
Benjamin

**Comment by vkuznet** [comment]
Benjamin,
I agree with all of your suggestions, they seems reasonable to me. Would you
agree that if we move validate into `make_notification` then we should also
through the exception? I don't mind to add warning/error message, we just need
to decide which behavior we'll present to clients.

I'm still traveling and can't sit down and code, so feel free to make a PR,
otherwise I'll take care of this later this week.

Best,
Valentin.

**Comment by stiegerb** [comment]
Ok, I'll prepare a PR, and we can iterate there.

I think the default behavior should be to return the notification and issue a warning or error in the logs. We can additionally offer to return also the result of the validation, so users could drop or collect those documents if they wanted.

In my opinion, the philosophy should be to check and notify users if their documents are failing validation, but to still send them, so to avoid data loss as much as possible.

**Comment by stiegerb** [comment]
Ok, I opened a PR with some changes that I found to work for the job monitoring. Please have a look and let me know what you think.

One thing I was considering: maybe we should perform validation only on **known** keys and ignore unknown keys. Especially in the case of job monitoring, there are a lot of keys we might not care about, and we don't have much control over what is added in the future. Maintenance of this could be a serious headache.

**Comment by stiegerb** [comment]
See also https://github.com/dmwm/cms-htcondor-es/pull/94

**Comment by vkuznet** [comment]
Regarding the keys. We should perform validation on keys which are present in schema. If key is unknown don't put it into a schema. But will MONIT accept a document with a key which was not declared before?

Regarding the maintenance, we need to maintain the schemas, and it will be responsibility of data-providers. And, if we don't care about some keys why should we put it into Monitoring?

**Comment by stiegerb** [comment]
Elasticsearch will reject documents if they have fields with conflicting types with respect to what's in the mappings for a given index. E.g. we had "CRAB_Id" mapped to an integer and started sending documents with values of "1-234" for "CRAB_Id", so they got rejected. So sending unknown fields is no problem as long as they don't then change their type.

The way Brian set up the code, it picks up any field that comes with the class ads, with a given list of fields that are validated and another list of fields that are dropped. I would suggest to do the same. I.e. the validation just yields a warning for previously unknown fields, but doesn't invalidate the document. Then we can monitor those warnings and decide which fields to add to validation and which to drop.

**Comment by vkuznet** [comment]
My question is why do we need to send key:value pairs which are not in a schema to MONIT? Moreover, if such attributes may change over time and we don't validate their types it can lead to document rejection. Why not to delete those attributes all together? I think it would be very easy to implement, just delete key from doc dict which is not found in a schema. Doing this way we will guarantee that these attributes will not be send to MONIT and at the same time we will ensure that only attributes which are present in schema will be there.

**Comment by leggerf** [comment]
IIUC it is a "feature" of Brian's code. But I second Valentin's opinion 
here. I think it is dangerous to allow for new keys that are not 
validated/outside of the schema. ES won't complain at first, but if then 
for some reason these keys we are not tracking/validating change type, 
and then we end up with document rejected. So allowing for unkwown keys 
is not very robust IMO

Il 15/02/2019 14:05, Valentin Kuznetsov ha scritto:

**Comment by stiegerb** [comment]
Of course we can also do it like that, and filter only the fields that we're interested in. It's a design decision of flexibility vs stability. The problem is that someone has to come up with a list of "interesting" fields.

I feel like we might be getting a bit too worried about losing documents here. Generally, I don't think we should expect field types to change very often. And we'd certainly notice when it happens.

**Comment by leggerf** [comment]
maybe we're looking at peanuts here, but I don't see the point of 
validating only half of a document.

Do I understand correctly that this problem only arise for the condor 
data? WOuld it be complicated to change the bahaviour?


Il 15/02/2019 16:05, Benjamin Stieger ha scritto:

**Comment by stiegerb** [comment]
I think for most clients, the list of fields is fairly well-controlled. For the job monitoring we just take anything that goes into the job class ads, so the issue arises there.

I would be trivial to put a whitelist of fields and drop everything else. The problem is to come up with the list. I would prefer to keep things as they are (at least for now), start running the validation, and watch for messages about unknown fields and then expand the schema as it goes.

**Comment by vkuznet** [comment]
Benjmain, I think my proposal to delete everything which is not present in schema does not contradict with your whitelist idea. If you need fields which you want to keep just adjust the schema and they will be kept even if you don't intend to use it for monitoring. If you agree it would be easy to implement deletion of attributes which does not belong to schema and I can do it quickly.

**Comment by stiegerb** [comment]
Hi Valentin,
The problem is not the implementation, it's that we're discussing a paradigm change for the job monitoring data that I'm not comfortable employing without further discussion. At the very least, I'd like to hear @bbockelm's opinion on this, since he's the one who originally came up with this.

Then, if we decide to delete fields that are not in the schema, we'll first have to validate the schema itself and make sure there is nothing missing before we start removing information.

**Comment by bbockelm** [comment]
Hi,

I see a strict schema as proposed (that is, forcing all accepted data to meet the schema) as a huge mistake.  The entirety of the job submission system is based on the idea of a schema-free design, allowing us to flexibly add specific attributes as the need arises.  This is really at the core of the system - and a monitoring system that can't allow this can't really represent the CMS computing system.

Including everything has shown to be immensely useful over the years, especially as it allows you to go back to data that you didn't realize you needed from months prior.  As someone who has had to use this data, I'd definitely NACK the approach of deleting data simply because the attributes aren't in a central schema.

That said, having a commonly understood set of attributes is obviously a good thing as it helps subsets of the data be more widely usable.  Just as a warning though: don't get too caught up in schema definitions.  The task at hand is monitoring, not schemas.  Schemas have a quickly lowering return on investment.

Brian

**Comment by vkuznet** [comment]
Brian,
I understand the flexibility concern you have but on another hand we can't go
blind and do not understand the data we store. For example change of data-type
in document can create HUGE issue when parsing TB/PB of data. The schema is not
to restrict the flexibility but rather to ensure that what we store is
consistent in terms of data-type.

May be my request to delete unused attributes is an overkill but at the end
there is no magic in these tools. If you put garbage in you'll get it back and you
know that. The amount of data we put does affect performance and more data we
put the more this issue will be prevalent.

We also saw the lost of documents and differences between different sources.
Schemas provide an insurance that we understand that data from our end
is ok and validated.

In order to do any analytics we must be sure that data fields we store
has consistent data types and structure. Otherwise there is no trust in such
analysis and monitoring.

So, my view that schema is important, but strict rule on attributes is a policy
decision.

Best,
Valentin.

**Comment by bbockelm** [comment]
> The schema is not to restrict the flexibility but rather to ensure that what we store is consistent in terms of data-type.

Right, and that's not going to be improved by implementing a strict rule on attributes.

> If you put garbage in you'll get it back and you know that.

Agreed.  However, whether or not attributes are enumerated a priori does not determine whether data is garbage or not.

Schemas are a tool -- of many -- to help improve data quality.  Let's use them where they shine along with other tools.

> So, my view that schema is important, but strict rule on attributes is a policy decision.

Agreed.  I suggest:

1.  We validate registered attributes against the schema.
2.  We keep additional attributes in reported documents.
3.  We periodically review unregistered attributes.  Unregistered attributes may become registered, become blacklisted (explicitly dropped), or stay unregistered.

**Comment by vkuznet** [comment]
Ok, agreed.

I would only add the following. We understand that
the non-validated attributes should be considered "as is", i.e.
- we can't guarantee that they will stay in all documents
- we can't guarantee that their data-type are well determine
- any aggregation information on these attributes can't be fully validated

**Comment by leggerf** [comment]
I think we should enforce the same degree of validation that happens on the MONIT side. ES accepts documents with new fields, but then reject documents if the type of this field change. So we lose documents, not just the fields. IIRC, last time the effect was around 10% of all documents, so this is not negligible. I don’t have a good idea of how to keep track of types of unknown fields in a fixed schema…I’d say one would need a DB for that but seems overkill. But if you guys have a good idea how to technically implement that, I think this is what we should do

**Comment by vkuznet** [comment]
Federica,
thanks for this reminder. The only way to keep up with attributes is to expand
the schema to include them. But this back to my original proposal if attributes
are not in a schema it is better to reject them since it can lead to loss of
documents as you correctly pointed out. And, it should be our policy decision.
If we want to guarantee that all documents we send will not be rejected by MONIT
we should remove unused attributes. On another hand there is no restriction
on schema, we just need to expand it if new attributes we want to keep up in
documents. Technically we create code that keep schema in cache which
periodically updated, so we can automate to load new schema.

Brian, it is your call again. I think from our part we can go either route.

**Comment by stiegerb** [comment]
I think we're missing a point here. Whatever we do with validation, we cannot stop a change of type in a pre-existing field (such as was the case with `CRAB_Id`) being handed to us by whoever writes it into the job class ads. Running validation and/or rejecting unknown fields doesn't change that, but it gives us a warning. (Also note that just because documents are rejected by ES doesn't mean we'll lose them altogether. We still have them aggregated on InfluxDB and raw on HDFS.)

I think Brian's proposal was clear. We put together a schema of fields that are whitelisted and validated and such that are blacklisted, and periodically update it. Fields outside the schema are kept, but give a warning in the logs. Fields that fail validation give an error in the logs, and possibly send an email warning.

In the code, the only thing we need to change is that unknown fields don't **fail** validation, but simply give a warning.

**Comment by vkuznet** [comment]
I just realized a "flaw" in current validation logic which we need to discuss what to do with it. In current implementation, see
https://github.com/dmwm/CMSMonitoring/blob/46153c980155820013f6ff1ac3f7debfc71e5834/src/python/CMSMonitoring/StompAMQ.py#L50
we use all available schema files until we find a correct one. This is so-called auto mode. Now, imaging that in this mode client will give us a document without specifying a schema. We'll loop over all schema files and scan each key. With current implementation of logging it means that all keys from the document will have printout that key is not valid for this schema. But this is because we use wrong schema file. So it would be "fake" message. With correct schema file hopefully only few logging messages due to unknown keys. And, that's create "fake" vs "true" message problem. I want to avoid "fake" messages, and the only way to do this is to force clients to specify which schema they need to use for their docs. We can use name patterns, e.g. if schema file name is JobMonitoring.schema, client should specify either full or partial name and we'll use matched schema. 

Benjamin, I need your feedback on this. It is mostly implementation issue and since you insist on logging messages we should do something about this possible issue to avoid fake messages and in general flood of them.

**Comment by stiegerb** [comment]
Hi Valentin,
Yes, that’s a good point. I think we should avoid the auto fallback option
as much as possible. Users can now specify a common schema for all docs or
even individual schemas for each notification they create. The schemas can
be in the common ‘schemas’ folder or just local files.

So for me we could just remove the fallback option of trying all schemas
and force users to provide/pick a schema. Furthermore we could let users
choose the log level for validation feedback.

Finally, discussing with Brian and Alan, it might be useful to have the
code return a list of offending fields rather than a bool for the
validation result. That way, users could choose to drop the offending
fields from the documents and retry validation before sending.

I can prepare a PR tomorrow.

Cheers,
Benjamin

**Comment by stiegerb** [comment]
#11 replaces the default "guessing" behavior with simply comparing subsequent documents to the first one. I figure that's better than not doing anything, so might be a better default option. And, users can choose the log level for the validation.

**Comment by stiegerb** [comment]
Added also the change in return value to #11. @vkuznet @leggerf  please have a look.

Note that i don't know what the jsonschema validation would return and whether it can be made to behave in the same way.
